# This is a default template for a post-install scriptlet.
# Uncomment only required functions and remove any functions
# you don't need (and this header).

## arg 1:  the new package version
pre_install() {
	true
}

## arg 1:  the new package version
post_install() {
	hwclock --systohc
	echo "en_US.UTF8 UTF-8" >/etc/locale.gen
	locale-gen
	if ! getent passwd cela >/dev/null; then
		useradd -m -G wheel,adm,rfkill,log,sys,systemd-journal,users,uucp,lp -s /bin/bash cela
	fi
	systemctl enable NetworkManager
	systemctl enable lxdm
	cp /usr/share/wafflepkg/krb5.conf /etc/krb5.conf
	cp /usr/share/wafflepkg/ssh_config /etc/ssh/ssh_config
	cp /usr/share/wafflepkg/pcmanfm.conf /etc/xdg/pcmanfm/LXDE/pcmanfm.conf
	sed -i "s/\# bg=.*/bg=\/usr\/share\/wafflepkg\/background.png/" /etc/lxdm/lxdm.conf
}

## arg 1:  the new package version
## arg 2:  the old package version
pre_upgrade() {
	true
}

## arg 1:  the new package version
## arg 2:  the old package version
post_upgrade() {
	post_install
}

## arg 1:  the old package version
pre_remove() {
	true
}

## arg 1:  the old package version
post_remove() {
	true
}
